[package]
name = "minimizer"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
clang = { version = "2.0.0", features = ["clang_10_0"] }
itertools = "0.14.0"
tqdm = "0.8.0"

[profile.release]
debug = true
lto = true
codegen-units = 1
